### ISSUE TITLE
Code highlighting does not work if the URL has query parameters

### ISSUE THREAD

**Issue by RoyalBingBong** [bbc/codext#6]
The code highlighting is not working if the request returns a  `content-type: text/plain`, but has a normal file extension in the URL.  
For example:  
* http://\<internal-repo\>/browse/src/foo/bar/baz.ts **works**
* http://\<internal-repo\>/browse/src/foo/bar/baz.ts?anything **doesn't work**

**Comment by PyvesB** [comment]
Hello @RoyalBingBong!

Thanks for reporting this. Indeed, we should probably refine how we extract the file extension, we don't account for query parameters at the moment (see [here](https://github.com/bbc/codext/blob/3c1a33779ec01b9ca3875c7c6db722a1cef56d49/src/content/content.js#L38)). Would you like to submit a pull request? Otherwise I'm sure @MikaLeppala or @danielthepope would be able to help out as I don't have access to a dev environnement at the moment. :wink: 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Codext 1.0.2 ships a fix for this issue! It's already available for Firefox users and will be published for Chrome in the coming days. Enjoy!
